# Generated by Django 3.2.12 on 2022-04-01 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isIndependant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('still_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('isCoop', models.BooleanField(blank=True, null=True)),
                ('isFinished', models.BooleanField(blank=True, null=True)),
                ('isOnline', models.BooleanField(blank=True, null=True)),
                ('isFree', models.BooleanField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/game/')),
                ('developer', models.ManyToManyField(blank=True, null=True, to='finder.Developer')),
                ('editor', models.ManyToManyField(blank=True, null=True, to='finder.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/licence/')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/platform/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=64)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/tag/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=320)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('xp', models.PositiveBigIntegerField(default=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('desc_text', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('account_creation', models.DateField(default=datetime.date(2022, 4, 1))),
                ('permission_level', models.PositiveSmallIntegerField()),
                ('picture_profile', models.ImageField(blank=True, null=True, upload_to='img/user/banner_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=datetime.date(2022, 4, 1))),
                ('validated', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='licence',
            field=models.ManyToManyField(blank=True, null=True, to='finder.Licence'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(blank=True, null=True, to='finder.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='finder.Tag'),
        ),
    ]
