# Generated by Django 3.2.12 on 2022-04-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20220405_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='finder/static/finder/img/platform/'),
        ),
        migrations.AddField(
            model_name='editor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='finder/static/finder/img/platform/'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_banner',
            field=models.ImageField(blank=True, null=True, upload_to='finder/static/finder/img/user/banner_pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_profile',
            field=models.ImageField(blank=True, null=True, upload_to='finder/static/finder/img/user/profile_pic'),
        ),
    ]
