# Generated by Django 3.2.12 on 2022-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20220405_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='picture',
            new_name='picture_banner',
        ),
        migrations.AddField(
            model_name='game',
            name='picture_gameplay',
            field=models.ImageField(blank=True, null=True, upload_to='finder/static/finder/img/game/'),
        ),
        migrations.AddField(
            model_name='game',
            name='picture_icon',
            field=models.ImageField(blank=True, null=True, upload_to='finder/static/finder/img/game/'),
        ),
    ]
