# Generated by Django 3.2.12 on 2022-04-06 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20220406_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_creation',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
