# Generated by Django 3.2.12 on 2022-04-06 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_alter_user_account_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_creation',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
