# Generated by Django 3.2.13 on 2022-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_alter_submission_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isHard',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='isMature',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
