# Generated by Django 3.2.12 on 2022-05-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20220503_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isInde',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
