# Generated by Django 3.2.12 on 2022-05-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_game_isinde'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
