# Generated by Django 3.2.12 on 2022-05-20 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_delete_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='submit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='submitter',
            field=models.ManyToManyField(blank=True, null=True, to='finder.User'),
        ),
        migrations.AddField(
            model_name='developer',
            name='validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='editor',
            name='submit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='editor',
            name='submitter',
            field=models.ManyToManyField(blank=True, null=True, to='finder.User'),
        ),
        migrations.AddField(
            model_name='editor',
            name='validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='submit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='submitter',
            field=models.ManyToManyField(blank=True, null=True, to='finder.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='submit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='submitter',
            field=models.ManyToManyField(blank=True, null=True, to='finder.User'),
        ),
        migrations.AddField(
            model_name='licence',
            name='validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='submit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='submitter',
            field=models.ManyToManyField(blank=True, null=True, to='finder.User'),
        ),
        migrations.AddField(
            model_name='platform',
            name='validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='submit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='submitter',
            field=models.ManyToManyField(blank=True, null=True, to='finder.User'),
        ),
        migrations.AddField(
            model_name='tag',
            name='validated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
